"""Detecting ROCA-vulnerable RSA keys (CVE-2017-13099... CVE-2017-15361).

The Infineon RSALib generated primes of the form ``p = k*M + (65537^a mod M)`` for a
fixed primorial ``M``, which makes the public modulus ``N = p*q`` a power of 65537 modulo
every prime factor of ``M``. That is a fingerprint: for each such small prime, ``N mod
prime`` must lie in the subgroup generated by 65537. A random modulus fails this for some
prime almost immediately, so a key that passes *every* one is ROCA-vulnerable -- its
private key can be recovered by a Coppersmith attack, however large the modulus.

Only the public modulus is needed, so this is a passive, deterministic check with no
oracle. The primes are the factors of the RSALib primorial; larger keys use a larger
primorial, but it is always a multiple of these, so the fingerprint holds for every size.
"""

from __future__ import annotations

_EXPONENT = 65537
#: The small primes whose product is the RSALib primorial (the first odd primes to 167).
_ROCA_PRIMES = [
    3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83,
    89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
]


def _powers(prime: int) -> frozenset:
    """The subgroup ``{65537**k mod prime}`` -- the residues a ROCA modulus may take."""
    residues = set()
    value = 1
    while value not in residues:
        residues.add(value)
        value = value * _EXPONENT % prime
    return frozenset(residues)


_SUBGROUPS = {prime: _powers(prime) for prime in _ROCA_PRIMES}


def is_roca_vulnerable(modulus: int) -> bool:
    """Whether an RSA modulus bears the ROCA fingerprint (CVE-2017-15361)."""
    if modulus <= 0:
        return False
    return all(modulus % prime in _SUBGROUPS[prime] for prime in _ROCA_PRIMES)
